import Head from "next/head";
import UploadWidget from "../Components/UploadWidget";
import Locator from "../Components/Locator";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <script
                    src="https://widget.cloudinary.com/v2.0/global/all.js"
                    type="text/javascript"></script>
            </Head>

            <Locator />
            <UploadWidget />
        </div>
    );
}
